Added Icon for advanced search.
AjoyTheBeast/AI_CostEstimation-Analysis pull request #10
Opened 2024-08-07 17:31 UTC by Mohitpremanii

Added icon for advanced search. Removed clicking events from panel heading.

2024-08-07 17:33 UTC, avjitbose1 approved these changes

2024-08-08 05:29 UTC, AjoyTheBeast requested changes
Please

2024-08-08 05:29 UTC, AjoyTheBeast commented on ACE/ACE_App/Views/ACE/Index.cshtml
> +
Mohit please remove this comment <!-- New -->

2024-08-08 05:32 UTC, AjoyTheBeast commented on ACE/ACE_App/Views/ACE/Index.cshtml
> +   <span class="dropdown-arrow glyphicon glyphicon-menu-down"></span> <!-- New -->
Remove this comment <!-- New -->

2024-08-08 06:35 UTC, AjoyTheBeast approved these changes

2024-08-08 06:35 UTC, merged